/* Generated By:JavaCC: Do not edit this line. HySoftTreeConstants.java Version 6.0_1 */
package HyRules;

public interface HySoftTreeConstants
{
  public int JJTCOMPILE = 0;
  public int JJTVOID = 1;
  public int JJTLIBRARYDECLARE = 2;
  public int JJTLOADDECLARE = 3;
  public int JJTVECVAR = 4;
  public int JJTINTVAR = 5;
  public int JJTCHARVAR = 6;
  public int JJTBOOLVAR = 7;
  public int JJTDOUBLEVAR = 8;
  public int JJTSTRINGVAR = 9;
  public int JJTOBJECTVAR = 10;
  public int JJTDATADEFINE = 11;
  public int JJTFUNLIB = 12;
  public int JJTFUNCTIONDEFINE = 13;
  public int JJTIFSTATEMENT = 14;
  public int JJTSTATEMENTCLAUSE = 15;
  public int JJTIFCONDITIONEXPR = 16;
  public int JJTNOTINORIN = 17;
  public int JJTFORSTATEMENT = 18;
  public int JJTWHILESTATEMENT = 19;
  public int JJTCONDITIONALEXPRESSION = 20;
  public int JJTCONDITIONALANDEXPRESSION = 21;
  public int JJTEQUALITYEXPRESSION = 22;
  public int JJTRELATIONALEXPRESSION = 23;
  public int JJTADDITIVEEXPRESSION = 24;
  public int JJTMULTIPLICATIVEEXPRESSION = 25;
  public int JJTUNARYEXPRESSION = 26;
  public int JJTPREFIXEXPRESSION = 27;
  public int JJTCASTEXPRESSION = 28;
  public int JJTPOSTFIXEXPRESSION = 29;
  public int JJTSTATEMENTEXPRESSION = 30;
  public int JJTCALLFUNCSTATEMENT = 31;
  public int JJTBREAKSTATEMENT = 32;
  public int JJTCONTINUESTATEMENT = 33;
  public int JJTRETURNSTATEMENT = 34;
  public int JJTRETURN2CLIENT = 35;
  public int JJTERROR_SKIPTO = 36;


  public String[] jjtNodeName = {
    "Compile",
    "void",
    "LibraryDeclare",
    "LoadDeclare",
    "VecVar",
    "IntVar",
    "CharVar",
    "BoolVar",
    "DoubleVar",
    "StringVar",
    "ObjectVar",
    "DataDefine",
    "FunLib",
    "FunctionDefine",
    "IfStatement",
    "StatementClause",
    "IfConditionExpr",
    "NotInorIn",
    "ForStatement",
    "WhileStatement",
    "ConditionalExpression",
    "ConditionalAndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "PrefixExpression",
    "CastExpression",
    "PostfixExpression",
    "StatementExpression",
    "CallFuncStatement",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "Return2Client",
    "error_skipto",
  };
}
/* JavaCC - OriginalChecksum=32f986540c2aa637c926c5d063980ac3 (do not edit this line) */
